version: "2"
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - containedctx
    - contextcheck
    - err113
    - errchkjson
    - errname
    - errorlint
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - goheader
    - goprintffuncname
    - gosec
    - gosmopolitan
    - misspell
    - nilerr
    - testpackage
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl
    - zerologlint
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10      
formatters:
  enable:
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
